version: '3.3'

services:
  web-frontend:
    build: ./frontend
    volumes:
    - ./frontend:/var/www/html
    ports:
    - 5000:80
  backend-db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./backend:/docker-entrypoint-init-db.d
    environment:
      MYSQL_DATABASE: mobiles
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5001:80
    environment:
      - PMA_ARBITRARY=1
  international-product:
    build: ./international_product
    ports:
    - 5002:80

